name: WDIO CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Start web server
      run: yarn dev

    - name: Wait for Server to Start
      run: sleep 10 # Waits for 10 seconds

    - name: Check if Server is Running
      run: curl -I localhost:[3000]

    - name: Show WebdriverIO Config
      run: cat ./wdio.conf.ts

    - name: Run WebdriverIO tests
      run: yarn wdio
