name: WDIO CI

on:
  push:
  workflow_dispatch:

jobs:
  WDIO_test_and_Allure_report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Start web server
      run: nohup yarn dev > /dev/null 2>&1 &
    
    - name: Wait for Server to Start
      run: sleep 10 # Waits for 10 seconds

    - name: Check if Server is Running
      run: curl -I localhost:3000

    - name: Run WebdriverIO tests
      run: yarn test
      continue-on-error: true
    
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
      
    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: allure-results-${{ github.run_number }}-${{ github.sha }}
    #     path: allure-report
    #     retention-days: 3

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history